apiVersion: v1
kind: Pod

metadata:
    name: nginx-pod
    labels:
        app: myapp
        tier: frontend
spec:
    containers:
        - name: nginx
          image: nginx
          ports:
              - containerPort: 80
# kubectl get pods
# kubectl get nodes
# kubectl get ns
# kubectl apply -f pods.yaml
