apiVersion: v1
kind: Service
metadata:
  name: myapp-nodeport-service
  labels:
    app: myapp
spec:
  selector:
    app: myapp
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30000
