apiVersion: v1
kind: Service
metadata:
  name: myapp-cluster-ip-service
spec:
  selector:
    app: myapp
  ports:
    - port: 80
      targetPort: 80
  type: ClusterIP
# kubectl apply -f service.yaml
# kubectl run test-pod --rm -it --image=busybox /bin/sh
# wget -qO- http://myapp-cluster-ip-service
